CREATE TABLE CARD_SUITS (
    SUIT_ID NUMBER NOT NULL,
    SUIT    VARCHAR2(255 BYTE),
    PRIMARY KEY (SUIT_ID)
);

COMMENT ON TABLE CARD_SUITS IS 'Contains possible values for card suit';
COMMENT ON COLUMN CARD_SUITS.SUIT_ID IS 'ID of suit';
COMMENT ON COLUMN CARD_SUITS.SUIT IS 'Suit name';

INSERT INTO CARD_SUIT (SUIT_ID, SUIT) VALUES (1,'spades');
INSERT INTO CARD_SUIT (SUIT_ID, SUIT) VALUES (2,'diamonds');
INSERT INTO CARD_SUIT (SUIT_ID, SUIT) VALUES (3,'clubs');
INSERT INTO CARD_SUIT (SUIT_ID, SUIT) VALUES (4,'hearts');

CREATE TABLE CARD_NUMBERS (
    CARD_NUMBER_ID NUMBER NOT NULL,
    CARD_NUMBER    VARCHAR2(255 BYTE),
    PRIMARY KEY (CARD_NUMBER_ID)
);

COMMENT ON TABLE CARD_NUMBERS IS 'Contains possible values for card number';
COMMENT ON COLUMN CARD_NUMBERS.CARD_NUMBER_ID IS 'ID of number';
COMMENT ON COLUMN CARD_NUMBERS.CARD_NUMBER IS 'number name';

INSERT INTO CARD_NUMBERS (CARD_NUMBER_ID, CARD_NUMBER) VALUES (1,'A');
INSERT INTO CARD_NUMBERS (CARD_NUMBER_ID, CARD_NUMBER) VALUES (2,'2');
INSERT INTO CARD_NUMBERS (CARD_NUMBER_ID, CARD_NUMBER) VALUES (3,'3');
INSERT INTO CARD_NUMBERS (CARD_NUMBER_ID, CARD_NUMBER) VALUES (4,'4');
INSERT INTO CARD_NUMBERS (CARD_NUMBER_ID, CARD_NUMBER) VALUES (5,'5');
INSERT INTO CARD_NUMBERS (CARD_NUMBER_ID, CARD_NUMBER) VALUES (6,'6');
INSERT INTO CARD_NUMBERS (CARD_NUMBER_ID, CARD_NUMBER) VALUES (7,'7');
INSERT INTO CARD_NUMBERS (CARD_NUMBER_ID, CARD_NUMBER) VALUES (8,'8');
INSERT INTO CARD_NUMBERS (CARD_NUMBER_ID, CARD_NUMBER) VALUES (9,'9');
INSERT INTO CARD_NUMBERS (CARD_NUMBER_ID, CARD_NUMBER) VALUES (10,'10');
INSERT INTO CARD_NUMBERS (CARD_NUMBER_ID, CARD_NUMBER) VALUES (11,'J');
INSERT INTO CARD_NUMBERS (CARD_NUMBER_ID, CARD_NUMBER) VALUES (12,'Q');
INSERT INTO CARD_NUMBERS (CARD_NUMBER_ID, CARD_NUMBER) VALUES (13,'K');

